version: '3.8'

services:
  frontend:
    image: frontend:latest
    build:                         
      context: ./     
      dockerfile: Dockerfile
    ports:
      - "80:80"   
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
