version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass sample
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/db/redis:/var/lib/redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/db/mysql:/var/lib/mysql
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sample
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/db/mongo:/var/lib/mongo
  backend:
    image: backend:latest
    ports:
      - "8080:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mysql
      - redis
      - mongo